name: BUILD SERVICE

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      nugetVersion:
        description: "Version for /p:Version and /p:AssemblyVersion"
        required: false
        default: "1.0.0"

env:
  # Provide these in repo or as org variables/secrets as appropriate
  ABBYFINEREADER_SERVICE_FOLDER: src
  ABBYFINEREADER_SDK_PROJECT_PATH: AbbyFineReader.Service/AbbyFineReader.Service.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set version
        id: ver
        run: |
          if [ -z "${{ github.event.inputs.nugetVersion }}" ]; then
            echo "nugetVersion=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
          else
            echo "nugetVersion=${{ github.event.inputs.nugetVersion }}" >> $GITHUB_OUTPUT
          fi

      - name: Restore
        run: |
          dotnet restore "${ABBYFINEREADER_SERVICE_FOLDER}/${ABBYFINEREADER_SDK_PROJECT_PATH}"

      - name: Build (Release)
        run: |
          dotnet build "${ABBYFINEREADER_SERVICE_FOLDER}/${ABBYFINEREADER_SDK_PROJECT_PATH}" \
            -c Release \
            /p:Version=${{ steps.ver.outputs.nugetVersion }} \
            /p:AssemblyVersion=${{ steps.ver.outputs.nugetVersion }}

      - name: Publish (self-contained=false)
        run: |
          dotnet publish "${ABBYFINEREADER_SERVICE_FOLDER}/${ABBYFINEREADER_SDK_PROJECT_PATH}" \
            -c Release \
            -o ./publish/

      - name: Package artifact
        run: |
          cd publish
          zip -r ../service.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: service
          path: service.zip
          if-no-files-found: error
          retention-days: 14
